### ISSUE TITLE
Open.mp masterlist issue.

### ISSUE THREAD

**Issue by nickdodd25** [openmultiplayer/web#100]
I noticed a odd issue with the masterlist on the website.

My server recently moved to a new ip. I added the new ip to the masterlist via the ip/domain add feature. My old ip that is no longer used shows the server as online, and the new ip seems to have been removed.

Old Ip:167.114.104.51:7777
New: 149.56.185.92:7777

**Comment by Southclaws** [comment]
https://open.mp/servers/167.114.104.51:7777
https://open.mp/servers/149.56.185.92:7777

The old one will disappear eventually assuming it goes offline.
