### ISSUE TITLE
Codeowners can no longer merge into the directories they own

### ISSUE THREAD

**Issue by iPollo** [openmultiplayer/web#114]
I checked with some codeowners and the same happened with them.

**Comment by Southclaws** [comment]
Not sure what's wrong, GitHub seems to think it works:

![image](https://user-images.githubusercontent.com/1636971/103381188-fba6a980-4ae2-11eb-9c7f-02203ebc3edd.png)

**Comment by daddyDOT** [comment]
I have the same issue, directory /bs/
![image](https://user-images.githubusercontent.com/65982671/103383624-ae7f0380-4af3-11eb-9c5b-7fd78e71f016.png)

**Comment by iPollo** [comment]
Probably its some branch protection rule, or an intern repo access configuration.

**Comment by daddyDOT** [comment]
Issue is fixed, I don't think it's necessary to keep it open @Southclaws .
