### ISSUE TITLE
Edit button for each docs page

### ISSUE THREAD

**Issue by Southclaws** [openmultiplayer/web#12]
Each page needs an "Edit this page" button that just directs to GitHub using the same file with `/edit/` in the path.

**Comment by coool9** [comment]
Why isn't this closed? There is already a 'help needed' needed which directs to github

**Comment by adib-yg** [comment]
![image](https://github.com/openmultiplayer/web/assets/92677767/9896f75c-6bdb-4905-b9b4-2f1f84555765)
