### ISSUE TITLE
Version warnings on some wiki pages near obsolete

### ISSUE THREAD

**Issue by JarnoKai** [openmultiplayer/web#144]
Whenever new functions were implemented in past SA:MP versions, the corresponding wiki pages got a box at the top warning programmers that the functions are new. These warnings have staid there, even all the way since 0.3a as in the RepairVehicle article. Considering that even the newest (supported) version of SA:MP, 0.3.7, was released way back in 2015, I find that it is fair to assume most readers in 2021 are running newer versions of the server.
I find it fair to mention in which version the function was added - both for a bit of history trivia and to preserve the information that's already there - but I definitely think it should perhaps be given a lot less attention than it currently gets. A tiny mention at the bottom of the article would be sufficient in my opinion.

**Comment by NermanLegacy** [comment]
This has been added a long time ago yet this issue still isn't closed, thanks for making this issue in the first place!
