### ISSUE TITLE
Cannot changing locale path to default.

### ISSUE THREAD

**Issue by Eiikirin** [openmultiplayer/web#20]
I cannot even access `open.mp` without `/id` path i mean always redirect to `/id` path as you can see in this gif below:
![steps](https://user-images.githubusercontent.com/55049217/99886663-0020ac80-2c71-11eb-831b-952fb39cb25d.gif)

**Comment by sondrekje** [comment]
https://github.com/openmultiplayer/web/pull/21 fixes this by including /en into the language select link for English even though it's the default language.
