### ISSUE TITLE
"https://open.mp/docs/scripting/functions/HTTP" NOT FOUND/UNEXPECTED ERROR

### ISSUE THREAD

**Issue by 7xwolfex** [openmultiplayer/web#217]
Upon accessing https://open.mp/docs/scripting/functions/HTTP , the following message is displayed:
Error!
File scripting/functions/HTTP (en) not found: Not found (scripting/functions/HTTP)

this problem occurs even with navigating under the Docs tab of the website:
Docs > Contents > Scripting > Functions > HTTP
the website returns "unexpected error" when the HTTP function documentation is accessed this way

**Comment by Southclaws** [comment]
It might have been the unfinished auth hook causing this, the page works fine after removing it: https://open.mp/docs/scripting/functions/HTTP
