### ISSUE TITLE
Add youtube and twitch links

### ISSUE THREAD

**Issue by Southclaws** [openmultiplayer/web#27]
To footer

**Comment by Southclaws** [comment]
https://github.com/sergioramos/remark-oembed

**Comment by WoutProvost** [comment]
Add Burgershot link

**Comment by leonardssh** [comment]
@Southclaws Is this issue still relevant? 

![image](https://user-images.githubusercontent.com/35312043/166113357-b2ab5a52-b31f-4c71-b176-c3947783ccaa.png)
