### ISSUE TITLE
Indonesia Translation Progress List

### ISSUE THREAD

**Issue by ghost** [openmultiplayer/web#32]
This issues will be updated everytime someone made ID translation updates on wiki.
I took lists from [#196](https://github.com/openmultiplayer/wiki/issues/196) migrating from https://github.com/openmultiplayer/wiki/issues/263

Hallo semuanya, disini aku meminta bantuan kalian untuk membantu aku untuk menerjemahkan wiki ini dengan bahasa indonesia, namun sebelum memulai membantu ada hal yang harus di sampaikan terlebih dahulu agar nantinya tidak salah dan tidak asal-asalan.

1. Usahakan jangan terlalu terpaku dengan google terjemahan, kalau tidak faham bisa tag @se8870 atau @rsetiawan7 atau bahkan orang yang kamu kenal.
1. Diperhatikan, diskusikan, dan cari tahu kata apa yang tepat untuk digunakan di dalam wiki ini.
1. Selalu beritahu bagian mu agar kita bisa membaginya bersama, tidak seenaknya untuk menterjemahkan suatu hal yang padahal itu sedang dikerjakan oleh orag lain.

Oh iya, ini akan selalu di update setiap ada yang translate indonesia di wiki, mau siapapun itu.
Tinggal komentar aja dibagian mana yang di update atau mention nanti bakal di merge secepatnya.

Itu saja yang bisa aku kasih tau, terimakasih telah membantu memberdayakan wiki ini 👏 

List Translation Pages:
client
- [x] Common Issues
- [x] Crash Addresses

meta
- [x] Contributing.md

scripting/callbacks
- [x] OnActorStreamIn.md
- [x] OnActorStreamOut.md
- [x] OnClientMessage.md
- [x] OnDialogResponse.md
- [x] OnEnterExitModShop.md
- [x] OnFilterScriptExit.md
- [x] OnFilterScriptInit.md
- [x] OnGameModeExit.md
- [x] OnGameModeInit.md
- [x] OnIncomingConnection.md
- [x] OnObjectMoved.md
- [x] OnPlayerClickMap.md
- [x] OnPlayerClickPlayer.md
- [x] OnPlayerClickPlayerTextDraw.md
- [x] OnPlayerClickTextDraw.md
- [x] OnPlayerCommandText.md
- [x] OnPlayerConnect.md
- [x] OnPlayerDeath.md
- [x] OnPlayerDisconnect.md
- [ ] OnPlayerEditAttachedObject.md
- [ ] OnPlayerEditObject.md
- [ ] OnPlayerEnterCheckpoint.md
- [ ] OnPlayerEnterRaceCheckpoint.md
- [ ] OnPlayerEnterVehicle.md
- [ ] OnPlayerExitVehicle.md
- [ ] OnPlayerExitedMenu.md
- [ ] OnPlayerFinishedDownloading.md
- [ ] OnPlayerGiveDamage.md
- [ ] OnPlayerGiveDamageActor.md
- [ ] OnPlayerInteriorChange.md
- [x] OnPlayerKeyStateChange.md
- [ ] OnPlayerLeaveCheckpoint.md
- [ ] OnPlayerLeaveRaceCheckpoint.md
- [ ] OnPlayerObjectMoved.md
- [ ] OnPlayerPickUpPickup.md
- [ ] OnPlayerRequestClass.md
- [ ] OnPlayerRequestDownload.md
- [ ] OnPlayerRequestSpawn.md
- [ ] OnPlayerSelectObject.md
- [ ] OnPlayerSelectedMenuRow.md
- [x] OnPlayerSpawn.md
- [ ] OnPlayerStateChange.md
- [x] OnPlayerStreamIn.md
- [x] OnPlayerStreamOut.md
- [x] OnPlayerTakeDamage.md
- [x] OnPlayerText.md
- [x] OnPlayerUpdate.md
- [ ] OnPlayerWeaponShot.md
- [ ] OnRconCommand.md
- [ ] OnRconLoginAttempt.md
- [ ] OnRecordingPlaybackEnd.md
- [ ] OnTrailerUpdate.md
- [ ] OnUnoccupiedVehicleUpdate.md
- [ ] OnVehicleDamageStatusUpdate.md
- [ ] OnVehicleDeath.md
- [ ] OnVehicleMod.md
- [ ] OnVehiclePaintjob.md
- [ ] OnVehicleRespray.md
- [ ] OnVehicleSirenStateChange.md
- [ ] OnVehicleSpawn.md
- [ ] OnVehicleStreamIn.md
- [ ] OnVehicleStreamOut.md

scripting/functions
- [ ] AddMenuItem.md
- [ ] AddPlayerClass.md
- [ ] AddPlayerClassEx.md
- [ ] AddSimpleModel.md
- [ ] AddSimpleModelTimed.md
- [ ] AddStaticPickup.md
- [ ] AddStaticVehicle.md
- [ ] AddStaticVehicleEx.md
- [ ] AddVehicleComponent.md
- [ ] AllowAdminTeleport.md
- [ ] AllowInteriorWeapons.md
- [ ] AllowPlayerTeleport.md
- [ ] ApplyActorAnimation.md
- [ ] ApplyAnimation.md
- [ ] Attach3DTextLabelToPlayer.md
- [ ] Attach3DTextLabelToVehicle.md
- [ ] AttachCameraToObject.md
- [ ] AttachCameraToPlayerObject.md
- [ ] AttachObjectToObject.md
- [ ] AttachObjectToPlayer.md
- [ ] AttachObjectToVehicle.md
- [ ] AttachPlayerObjectToPlayer.md
- [ ] AttachPlayerObjectToVehicle.md
- [ ] AttachTrailerToVehicle.md
- [ ] Ban.md
- [ ] BanEx.md
- [ ] BlockIpAddress.md
- [ ] CallLocalFunction.md
- [ ] CallRemoteFunction.md
- [ ] CancelEdit.md
- [ ] CancelSelectTextDraw.md
- [ ] ChangeVehicleColor.md
- [ ] ChangeVehiclePaintjob.md
- [ ] ClearActorAnimations.md
- [ ] ClearAnimations.md
- [ ] ConnectNPC.md
- [ ] Create3DTextLabel.md
- [ ] CreateActor.md
- [ ] CreateExplosion.md
- [ ] CreateExplosionForPlayer.md
- [ ] CreateMenu.md
- [ ] CreateObject.md
- [ ] CreatePickup.md
- [ ] CreatePlayer3DTextLabel.md
- [ ] CreatePlayerObject.md
- [ ] CreatePlayerTextDraw.md
- [ ] CreateVehicle.md
- [ ] Delete3DTextLabel.md
- [ ] DeletePVar.md
- [ ] DeletePlayer3DTextLabel.md
- [ ] DeleteSVar.md
- [ ] DestroyActor.md
- [ ] DestroyMenu.md
- [ ] DestroyObject.md
- [ ] DestroyPickup.md
- [ ] DestroyPlayerObject.md
- [ ] DestroyVehicle.md
- [ ] DetachTrailerFromVehicle.md
- [ ] DisableInteriorEnterExits.md
- [ ] DisableMenu.md
- [ ] DisableMenuRow.md
- [ ] DisableNameTagLOS.md
- [ ] DisablePlayerCheckpoint.md
- [ ] DisablePlayerRaceCheckpoint.md
- [ ] DisableRemoteVehicleCollisions.md
- [ ] EditAttachedObject.md
- [ ] EditObject.md
- [ ] EditPlayerObject.md
- [ ] EnablePlayerCameraTarget.md
- [ ] EnableStuntBonusForAll.md
- [ ] EnableStuntBonusForPlayer.md
- [ ] EnableTirePopping.md
- [ ] EnableVehicleFriendlyFire.md
- [ ] EnableZoneNames.md
- [ ] FindModelFileNameFromCRC.md
- [ ] FindTextureFileNameFromCRC.md
- [ ] ForceClassSelection.md
- [ ] GameModeExit.md
- [ ] GameTextForAll.md
- [ ] GameTextForPlayer.md
- [ ] GangZoneCreate.md
- [ ] GangZoneDestroy.md
- [ ] GangZoneFlashForAll.md
- [ ] GangZoneFlashForPlayer.md
- [ ] GangZoneHideForAll.md
- [ ] GangZoneHideForPlayer.md
- [ ] GangZoneShowForAll.md
- [ ] GangZoneShowForPlayer.md
- [ ] GangZoneStopFlashForAll.md
- [ ] GangZoneStopFlashForPlayer.md
- [ ] GetActorFacingAngle.md
- [ ] GetActorHealth.md
- [ ] GetActorPoolSize.md
- [ ] GetActorPos.md
- [ ] GetActorVirtualWorld.md
- [ ] GetAnimationName.md
- [ ] GetConsoleVarAsBool.md
- [ ] GetConsoleVarAsInt.md
- [ ] GetConsoleVarAsString.md
- [ ] GetGravity.md
- [ ] GetGravity_FR.md
- [ ] GetMaxPlayers.md
- [ ] GetNetworkStats.md
- [ ] GetObjectModel.md
- [ ] GetObjectPos.md
- [ ] GetObjectRot.md
- [ ] GetPVarFloat.md
- [ ] GetPVarInt.md
- [ ] GetPVarNameAtIndex.md
- [ ] GetPVarString.md
- [ ] GetPVarType.md
- [ ] GetPVarsUpperIndex.md
- [ ] GetPlayerAmmo.md
- [ ] GetPlayerAmmo_DE.md
- [ ] GetPlayerAnimationIndex.md
- [ ] GetPlayerArmour.md
- [ ] GetPlayerCameraAspectRatio.md
- [ ] GetPlayerCameraFrontVector.md
- [ ] GetPlayerCameraMode.md
- [ ] GetPlayerCameraPos.md
- [ ] GetPlayerCameraTargetActor.md
- [ ] GetPlayerCameraTargetObject.md
- [ ] GetPlayerCameraTargetPlayer.md
- [ ] GetPlayerCameraTargetVehicle.md
- [ ] GetPlayerCameraUpVector.md
- [ ] GetPlayerCameraZoom.md
- [ ] GetPlayerColor.md
- [ ] GetPlayerCustomSkin.md
- [ ] GetPlayerDistanceFromPoint.md
- [ ] GetPlayerDrunkLevel.md
- [ ] GetPlayerFacingAngle.md
- [ ] GetPlayerFightingStyle.md
- [ ] GetPlayerHealth.md
- [ ] GetPlayerInterior.md
- [ ] GetPlayerIp.md
- [ ] GetPlayerKeys.md
- [ ] GetPlayerKeys_FR.md
- [ ] GetPlayerLastShotVectors.md
- [ ] GetPlayerMenu.md
- [ ] GetPlayerMoney.md
- [ ] GetPlayerName.md
- [ ] GetPlayerNetworkStats.md
- [ ] GetPlayerObjectModel.md
- [ ] GetPlayerObjectPos.md
- [ ] GetPlayerObjectRot.md
- [ ] GetPlayerPing.md
- [ ] GetPlayerPoolSize.md
- [ ] GetPlayerPos.md
- [ ] GetPlayerScore.md
- [ ] GetPlayerSkin.md
- [ ] GetPlayerSpecialAction.md
- [ ] GetPlayerState.md
- [ ] GetPlayerSurfingObjectID.md
- [ ] GetPlayerSurfingVehicleID.md
- [ ] GetPlayerTargetActor.md
- [ ] GetPlayerTargetPlayer.md
- [ ] GetPlayerTeam.md
- [ ] GetPlayerTime.md
- [ ] GetPlayerVehicleID.md
- [ ] GetPlayerVehicleSeat.md
- [ ] GetPlayerVelocity.md
- [ ] GetPlayerVersion.md
- [ ] GetPlayerVirtualWorld.md
- [ ] GetPlayerWantedLevel.md
- [ ] GetPlayerWeapon.md
- [ ] GetPlayerWeaponData.md
- [ ] GetPlayerWeaponState.md
- [ ] GetSVarFloat.md
- [ ] GetSVarInt.md
- [ ] GetSVarNameAtIndex.md
- [ ] GetSVarString.md
- [ ] GetSVarType.md
- [ ] GetSVarsUpperIndex.md
- [ ] GetServerTickRate.md
- [ ] GetServerVarAsBool.md
- [ ] GetServerVarAsInt.md
- [ ] GetServerVarAsString.md
- [ ] GetTickCount.md
- [ ] GetVehicleComponentInSlot.md
- [ ] GetVehicleComponentType.md
- [ ] GetVehicleDamageStatus.md
- [ ] GetVehicleDistanceFromPoint.md
- [ ] GetVehicleHealth.md
- [ ] GetVehicleModel.md
- [ ] GetVehicleModelInfo.md
- [ ] GetVehicleParamsCarDoors.md
- [ ] GetVehicleParamsCarWindows.md
- [ ] GetVehicleParamsEx.md
- [ ] GetVehicleParamsSirenState.md
- [ ] GetVehiclePoolSize.md
- [ ] GetVehiclePos.md
- [ ] GetVehicleRotationQuat.md
- [ ] GetVehicleTrailer.md
- [ ] GetVehicleVelocity.md
- [ ] GetVehicleVirtualWorld.md
- [ ] GetVehicleZAngle.md
- [ ] GetWeaponName.md
- [ ] GivePlayerMoney.md
- [ ] GivePlayerWeapon.md
- [ ] HTTP.md
- [ ] HideMenuForPlayer.md
- [ ] InterpolateCameraLookAt.md
- [ ] InterpolateCameraPos.md
- [ ] IsActorInvulnerable.md
- [ ] IsActorStreamedIn.md
- [ ] IsObjectMoving.md
- [ ] IsPlayerAdmin.md
- [ ] IsPlayerAttachedObjectSlotUsed.md
- [ ] IsPlayerConnected.md
- [ ] IsPlayerInAnyVehicle.md
- [ ] IsPlayerInCheckpoint.md
- [ ] IsPlayerInRaceCheckpoint.md
- [ ] IsPlayerInRangeOfPoint.md
- [ ] IsPlayerInVehicle.md
- [ ] IsPlayerNPC.md
- [ ] IsPlayerObjectMoving.md
- [ ] IsPlayerStreamedIn.md
- [ ] IsTrailerAttachedToVehicle.md
- [ ] IsValidActor.md
- [ ] IsValidMenu.md
- [ ] IsValidObject.md
- [ ] IsValidPlayerObject.md
- [ ] IsValidVehicle.md
- [ ] IsVehicleStreamedIn.md
- [ ] Kick.md
- [ ] KillTimer.md
- [ ] LimitGlobalChatRadius.md
- [ ] LimitPlayerMarkerRadius.md
- [ ] LinkVehicleToInterior.md
- [ ] ManualVehicleEngineAndLights.md
- [ ] MoveObject.md
- [ ] MovePlayerObject.md
- [ ] NetStats_BytesReceived.md
- [ ] NetStats_BytesSent.md
- [ ] NetStats_ConnectionStatus.md
- [ ] NetStats_GetConnectedTime.md
- [ ] NetStats_GetIpPort.md
- [ ] NetStats_MessagesReceived.md
- [ ] NetStats_MessagesRecvPerSecond.md
- [ ] NetStats_MessagesSent.md
- [ ] NetStats_PacketLossPercent.md
- [ ] PlayAudioStreamForPlayer.md
- [ ] PlayCrimeReportForPlayer.md
- [ ] PlayerPlaySound.md
- [ ] PlayerSpectatePlayer.md
- [ ] PlayerSpectateVehicle.md
- [ ] PlayerTextDrawAlignment.md
- [ ] PlayerTextDrawBackgroundColor.md
- [ ] PlayerTextDrawBoxColor.md
- [ ] PlayerTextDrawColor.md
- [ ] PlayerTextDrawDestroy.md
- [ ] PlayerTextDrawFont.md
- [ ] PlayerTextDrawHide.md
- [ ] PlayerTextDrawLetterSize.md
- [ ] PlayerTextDrawSetOutline.md
- [ ] PlayerTextDrawSetPreviewModel.md
- [ ] PlayerTextDrawSetPreviewRot.md
- [ ] PlayerTextDrawSetPreviewVehCol.md
- [ ] PlayerTextDrawSetProportional.md
- [ ] PlayerTextDrawSetSelectable.md
- [ ] PlayerTextDrawSetShadow.md
- [ ] PlayerTextDrawSetString.md
- [ ] PlayerTextDrawShow.md
- [ ] PlayerTextDrawTextSize.md
- [ ] PlayerTextDrawUseBox.md
- [ ] PutPlayerInVehicle.md
- [ ] RedirectDownload.md
- [ ] RemoveBuildingForPlayer.md
- [ ] RemovePlayerAttachedObject.md
- [ ] RemovePlayerFromVehicle.md
- [ ] RemovePlayerMapIcon.md
- [ ] RemoveVehicleComponent.md
- [ ] RepairVehicle.md
- [ ] ResetPlayerMoney.md
- [ ] ResetPlayerWeapons.md
- [ ] SHA256_PassHash.md
- [ ] SelectObject.md
- [ ] SelectTextDraw.md
- [ ] SendClientMessage.md
- [ ] SendClientMessageToAll.md
- [ ] SendDeathMessage.md
- [ ] SendDeathMessageToPlayer.md
- [ ] SendPlayerMessageToAll.md
- [ ] SendPlayerMessageToPlayer.md
- [ ] SendRconCommand.md
- [ ] SetActorFacingAngle.md
- [ ] SetActorHealth.md
- [ ] SetActorInvulnerable.md
- [ ] SetActorPos.md
- [ ] SetActorVirtualWorld.md
- [ ] SetCameraBehindPlayer.md
- [ ] SetDeathDropAmount.md
- [ ] SetGameModeText.md
- [ ] SetGravity.md
- [ ] SetMenuColumnHeader.md
- [ ] SetNameTagDrawDistance.md
- [ ] SetObjectMaterial.md
- [ ] SetObjectMaterialText.md
- [ ] SetObjectNoCameraCol.md
- [ ] SetObjectPos.md
- [ ] SetObjectRot.md
- [ ] SetObjectsDefaultCameraCol.md
- [ ] SetPVarFloat.md
- [ ] SetPVarInt.md
- [ ] SetPVarString.md
- [ ] SetPlayerAmmo.md
- [ ] SetPlayerArmedWeapon.md
- [ ] SetPlayerArmour.md
- [ ] SetPlayerAttachedObject.md
- [ ] SetPlayerCameraLookAt.md
- [ ] SetPlayerCameraPos.md
- [ ] SetPlayerChatBubble.md
- [ ] SetPlayerCheckpoint.md
- [ ] SetPlayerColor.md
- [ ] SetPlayerDrunkLevel.md
- [ ] SetPlayerFacingAngle.md
- [ ] SetPlayerFightingStyle.md
- [ ] SetPlayerHealth.md
- [ ] SetPlayerHoldingObject.md
- [ ] SetPlayerInterior.md
- [ ] SetPlayerMapIcon.md
- [ ] SetPlayerMarkerForPlayer.md
- [ ] SetPlayerName.md
- [ ] SetPlayerObjectMaterial.md
- [ ] SetPlayerObjectMaterialText.md
- [ ] SetPlayerObjectNoCameraCol.md
- [ ] SetPlayerObjectPos.md
- [ ] SetPlayerObjectRot.md
- [ ] SetPlayerPos.md
- [ ] SetPlayerPosFindZ.md
- [ ] SetPlayerRaceCheckpoint.md
- [ ] SetPlayerScore.md
- [ ] SetPlayerShopName.md
- [ ] SetPlayerSkillLevel.md
- [ ] SetPlayerSkin.md
- [ ] SetPlayerSpecialAction.md
- [ ] SetPlayerTeam.md
- [ ] SetPlayerTime.md
- [ ] SetPlayerVelocity.md
- [ ] SetPlayerVirtualWorld.md
- [ ] SetPlayerWantedLevel.md
- [ ] SetPlayerWeather.md
- [ ] SetPlayerWorldBounds.md
- [ ] SetSVarFloat.md
- [ ] SetSVarInt.md
- [ ] SetSVarString.md
- [ ] SetSpawnInfo.md
- [ ] SetTeamCount.md
- [ ] SetTimer.md
- [ ] SetTimerEx.md
- [ ] SetVehicleAngularVelocity.md
- [ ] SetVehicleHealth.md
- [ ] SetVehicleNumberPlate.md
- [ ] SetVehicleParamsCarDoors.md
- [ ] SetVehicleParamsCarWindows.md
- [ ] SetVehicleParamsEx.md
- [ ] SetVehicleParamsForPlayer.md
- [ ] SetVehiclePos.md
- [ ] SetVehicleToRespawn.md
- [ ] SetVehicleVelocity.md
- [ ] SetVehicleVirtualWorld.md
- [ ] SetVehicleZAngle.md
- [ ] SetWeather.md
- [ ] SetWorldTime.md
- [ ] ShowMenuForPlayer.md
- [ ] ShowNameTags.md
- [ ] ShowPlayerDialog.md
- [ ] ShowPlayerMarkers.md
- [ ] ShowPlayerNameTagForPlayer.md
- [ ] SpawnPlayer.md
- [ ] StartRecordingPlayerData.md
- [ ] StopAudioStreamForPlayer.md
- [ ] StopObject.md
- [ ] StopPlayerHoldingObject.md
- [ ] StopPlayerObject.md
- [ ] StopRecordingPlayerData.md
- [ ] TextDrawAlignment.md
- [ ] TextDrawBackgroundColor.md
- [ ] TextDrawBoxColor.md
- [ ] TextDrawColor.md
- [ ] TextDrawCreate.md
- [ ] TextDrawDestroy.md
- [ ] TextDrawFont.md
- [ ] TextDrawHideForAll.md
- [ ] TextDrawHideForPlayer.md
- [ ] TextDrawLetterSize.md
- [ ] TextDrawSetOutline.md
- [ ] TextDrawSetPreviewModel.md
- [ ] TextDrawSetPreviewRot.md
- [ ] TextDrawSetPreviewVehCol.md
- [ ] TextDrawSetProportional.md
- [ ] TextDrawSetSelectable.md
- [ ] TextDrawSetShadow.md
- [ ] TextDrawSetString.md
- [ ] TextDrawShowForAll.md
- [ ] TextDrawShowForPlayer.md
- [ ] TextDrawTextSize.md
- [ ] TextDrawUseBox.md
- [ ] Tickcount.md
- [ ] TogglePlayerClock.md
- [ ] TogglePlayerControllable.md
- [ ] TogglePlayerSpectating.md
- [ ] UnBlockIpAddress.md
- [ ] Update3DTextLabelText.md
- [ ] UpdatePlayer3DTextLabelText.md
- [ ] UpdateVehicleDamageStatus.md
- [ ] UsePlayerPedAnims.md
- [ ] VectorSize.md
- [ ] acos.md
- [ ] asin.md
- [ ] atan.md
- [ ] atan2.md
- [ ] clamp.md
- [ ] db_close.md
- [ ] db_debug_openfiles.md
- [ ] db_debug_openresults.md
- [ ] db_field_name.md
- [ ] db_free_result.md
- [ ] db_get_field.md
- [ ] db_get_field_assoc.md
- [ ] db_get_field_assoc_float.md
- [ ] db_get_field_assoc_int.md
- [ ] db_get_field_float.md
- [ ] db_get_field_int.md
- [ ] db_get_mem_handle.md
- [ ] db_get_result_mem_handle.md
- [ ] db_next_row.md
- [ ] db_num_fields.md
- [ ] db_num_rows.md
- [ ] db_open.md
- [ ] db_query.md
- [ ] deleteproperty.md
- [ ] existproperty.md
- [ ] fblockread.md
- [ ] fblockwrite.md
- [ ] fclose.md
- [ ] fexist.md
- [ ] fgetchar.md
- [ ] flength.md
- [ ] float.md
- [ ] floatabs.md
- [ ] floatadd.md
- [ ] floatcmp.md
- [ ] floatcos.md
- [ ] floatdiv.md
- [ ] floatfract.md
- [ ] floatlog.md
- [ ] floatmul.md
- [ ] floatpower.md
- [ ] floatround.md
- [ ] floatsin.md
- [ ] floatsqroot.md
- [ ] floatstr.md
- [ ] floatsub.md
- [ ] floattan.md
- [ ] fmatch.md
- [ ] fopen.md
- [ ] format.md
- [ ] fputchar.md
- [ ] fread.md
- [ ] fremove.md
- [ ] fseek.md
- [ ] ftemp.md
- [ ] funcidx.md
- [ ] fwrite.md
- [ ] getarg.md
- [ ] getdate.md
- [ ] getproperty.md
- [ ] gettime.md
- [ ] gpci.md
- [ ] heapspace.md
- [ ] index.md
- [ ] ispacked.md
- [ ] listenport.md
- [ ] max.md
- [ ] memcpy.md
- [ ] min.md
- [ ] numargs.md
- [ ] print.md
- [ ] printf.md
- [ ] random.md
- [ ] sendpacket.md
- [ ] sendstring.md
- [ ] setarg.md
- [ ] setproperty.md
- [ ] strcat.md
- [ ] strcmp.md
- [ ] strdel.md
- [ ] strfind.md
- [ ] strins.md
- [ ] strlen.md
- [ ] strmid.md
- [ ] strpack.md
- [ ] strunpack.md
- [ ] strval.md
- [ ] swapchars.md
- [ ] tolower.md
- [ ] toupper.md
- [ ] uudecode.md
- [ ] uuencode.md
- [ ] valstr.md

scripting/language
- [ ] ControlStructures.md
- [ ] Directives.md
- [ ] Initialisers.md
- [ ] Operators.md
- [ ] Statements.md
- [ ] Style.md
- [ ] Tags.md

scripting/resources
- [ ] anglemodes.md
- [ ] animations.md
- [ ] bodyparts.md
- [x] boneid.md
- [x] bullethittypes.md
- [ ] cameracutstyles.md
- [ ] cameramodes.md
- [ ] carcomponentid.md
- [ ] clicksources.md
- [ ] colorslist.md
- [ ] connectionstatus.md
- [ ] crimelist.md
- [x] damagestatus.md
- [x] dialogstyles.md
- [ ] doorstates.md
- [ ] escapecodes.md
- [x] explosionlist.md
- [ ] fightingstyles.md
- [ ] gametextstyles.md
- [ ] glossary.md
- [ ] hexcolors.md
- [ ] interiorids.md
- [ ] keys.md
- [ ] lightstates.md
- [ ] limits.md
- [x] mapicons.md
- [x] mapiconstyles.md
- [x] markermodes.md
- [ ] materialtextalignment.md
- [ ] materialtextsizes.md
- [ ] networkstats.md
- [x] objecteditionresponsetypes.md
- [ ] colors.md
- [x] pickupids.md
- [x] pickuptypes.md
- [ ] playerstates.md
- [ ] pvartypes.md
- [ ] recordtypes.md
- [ ] samp_objects.md
- [ ] selectobjecttypes.md
- [x] shopnames.md
- [ ] skins.md
- [ ] ids.md
- [ ] specialactions.md
- [ ] spectatemodes.md
- [ ] start.md
- [x] startingids.md
- [x] textalignments.md
- [ ] textdraws.md
- [ ] textdrawsprites.md
- [x] tirestates.md
- [x] vehiclecolorid.md
- [x] vehiclehealth.md
- [x] vehicleid.md
- [x] vehicleinformationtypes.md
- [x] vendingmachines.md
- [x] weaponids.md
- [x] weaponskills.md
- [x] weaponstates.md
- [x] weatherid.md

scripting/resources/_server
- [x] controllingaserver.md
- [x] lagcompensation.md
- [x] remoteconsole.md
- [x] server.cfg.md

tutorials
- [ ] AdvancedStructures.md
- [ ] Binary.md
- [x] _tutorials.md
- [x] colorfix.md
- [ ] cooldowns.md
- [x] MenuGuide.md
- [ ] perplayervariablesystem.md
- [ ] servervariablesystem.md
- [ ] stringmanipulation.md

**Comment by rsetiawan7** [comment]
I'll start to translate some functions

- [ ] AddStaticPickup.md
- [ ] AddStaticVehicle.md
- [ ] AddStaticVehicleEx.md
- [ ] AddVehicleComponent.md
- [ ] AllowAdminTeleport.md
- [ ] Ban.md
- [ ] BanEx.md
- [ ] CreateObject.md
- [ ] CreatePickup.md
- [ ] GetPlayerHealth.md
- [ ] GetPlayerInterior.md
- [ ] GetPlayerIp.md
- [ ] GetPlayerKeys.md
- [ ] GetPlayerMoney.md
- [ ] GetPlayerName.md

**Comment by AthallahDzaki** [comment]
i'll start to translate some callback
- [ ] OnPlayerStateChange.md
- [ ] OnPlayerStreamIn.md
- [ ] OnPlayerStreamOut.md
- [ ] OnPlayerTakeDamage.md

**Comment by Eiikirin** [comment]
I'm finalizing untranslated callbac left, so please focus on Function instead 😄

**Comment by Southclaws** [comment]
#348
