### ISSUE TITLE
English language button doesn't redirect to the correct route

### ISSUE THREAD

**Issue by MicheleLaBarbera** [openmultiplayer/web#33]
My browser language is set to **Italian**, so if I go on open.mp/ it'll redirects me to open.mp/it. 

When I click the language selection button to select the **English** language, it won't redirect to open.mp/en but instead it redirects to open.mp/

Steps to reproduce the bug:

1. Set your browser language to one that isn't **English**;
2. Click the button to select the language;
3. Select **English**.

**Comment by sondrekje** [comment]
This is the same issue as issue #21 and there is an open PR to fix it.
