### ISSUE TITLE
Docs search API should take partial page names into account

### ISSUE THREAD

**Issue by Vince0789** [openmultiplayer/web#339]
As the title implies, the search API should also search for partial page names.

For instance:

`GET https://api.open.mp/docs/search?q=TextDrawHide`

Expected results:
* TextDrawHideForPlayer
* TextDrawHideForAll
* PlayerTextDrawHide

Actual results:
None.

**Comment by Southclaws** [comment]
This kind of works, not partials yet (because indexing partials is actually awkward because of how text indexing actually works under the hood)

Pascal case splitting for keywords was done though, so `https://api.open.mp/docs/search?q=TextDraw+Hide`  works

**Comment by Southclaws** [comment]
done some splitting logic for queries that contain PascalCase and snake_case searches, see comment:

	// Tag query splits the query string by PascalCase or snake_case and uses
	// the component parts as tags. This means you can search
	// `TextDrawShowForPlayer` and the underlying query searches for:
	// ["text", "draw", "show", "for", "player"]. When this is combined with
	// other query types, it increases the chances of getting relevant results.
