### ISSUE TITLE
speech synthesizer

### ISSUE THREAD

**Issue by Dmitry7721** [openmultiplayer/web#340]
add the function of converting speech to text and text to speech (sounding with any voice of your choice), because some servers do not want to add voice chat, well, or the players themselves may not want to. This technology is available on windows 10 from Microsoft in the Xbox application, but does not work in all games, I know it works in Sea of thieves
![Screenshot_2021-05-18-16-43-24-04](https://user-images.githubusercontent.com/84472456/118867572-e7c1df80-b8eb-11eb-9f71-ea794f2fcc11.jpg)

**Comment by Dmitry7721** [comment]
> add the function of converting speech to text and text to speech (sounding with any voice of your choice), because some servers do not want to add voice chat, well, or the players themselves may not want to. This technology is available on windows 10 from Microsoft in the Xbox application, but does not work in all games, I know it works in Sea of thieves
![Uploading Screenshot_2021-05-18-08-59-48-15.jpg…]()

**Comment by Southclaws** [comment]
Definitely possible, and worth considering!

However, this repository is for the _web_ services, we'll start taking suggestions for new features post launch.
