### ISSUE TITLE
Posting a forum topic (reply) failure: The request did not have any authentication information with it.

### ISSUE THREAD

**Issue by Kwarde666** [openmultiplayer/web#392]
Whenever I attempt to write a post (whether it's a reply to an existing topic or creating a new one) I get that error message.
The request did not have any authentication information with it.

Account was created/logged in using Discord (using Github failed because it reported no e-mail address was available, or something like that).

Couldn't find similar issues, if I searched wrongly ("is:issue authentication") then sorry in advance

**Comment by Kwarde666** [comment]
It worked today (noticed posts were deleted so tried it again)

**Comment by Southclaws** [comment]
Thanks for the report anyway, we definitely need to work on some better error messages and maybe get Sentry.io set up for remote debugging of problems.

OAuth is a bit weird sometimes, and we don't handle every single corner case.
