### ISSUE TITLE
Wiki - Edit link

### ISSUE THREAD

**Issue by pkfln** [openmultiplayer/web#396]
Add a direct link to edit a wiki page.

Example:
https://open.mp/docs/scripting/functions/GangZoneDestroy contains a link somewhere that links to https://github.com/openmultiplayer/web/edit/master/docs/scripting/functions/GangZoneDestroy.md

**Comment by Southclaws** [comment]
Good shout, I forgot about this entirely!

Shouldn't be too difficult, since the paths match the same.

**Comment by adib-yg** [comment]
The issue has already been solved. 
I have closed this issue as completed.

![image](https://github.com/openmultiplayer/web/assets/92677767/3e048b29-5842-4387-8c40-a89a54a85ae5)
