### ISSUE TITLE
Skins and Crime List information

### ISSUE THREAD

**Issue by kkmzero** [openmultiplayer/web#419]
I found two possible mistakes in docs/resources.

- In Skins page (https://open.mp/docs/scripting/resources/skins) there is wrong image of skin with ID 167 - Cluckin' Bell Worker (https://assets.open.mp/assets/images/skins/167.png). I would fix this but I don't have the correct image for model wmybell.

- In Crime List page (https://open.mp/docs/scripting/resources/crimelist) the crime with ID 4 - Emergency road repairs needed, is very likely not 10-47 but 10-37 - Investigate suspicious vehicle. I tested it recently and it sounds to me like 10-37 but I'm not 100% sure since crime report sounds in San Andreas can be quite hard to understand.

I would be grateful if anyone can check if any of this is valid. Skins are properly listed in archived SA:MP wiki but crime report list is identical.

**Comment by adib-yg** [comment]
> In Crime List page (https://open.mp/docs/scripting/resources/crimelist) the crime with ID 4 - Emergency road repairs needed, is very likely not 10-47 but 10-37 - Investigate suspicious vehicle. I tested it recently and it sounds to me like 10-37 but I'm not 100% sure since crime report sounds in San Andreas can be quite hard to understand.

I played crime report id 4. I confirm it should be 10-37
