### ISSUE TITLE
Pagination indexing error

### ISSUE THREAD

**Issue by cudlpnda** [openmultiplayer/web#500]
Pagination on the main thread view is 0 indexed i.e. when I go to a page that is greater than 1 and click back on page 1, it gives an error.
![kKgxuZlkze](https://user-images.githubusercontent.com/48310612/142983027-c7ee1fb9-9fcb-4b53-a010-6aa241fcbbf7.gif)

**Comment by Southclaws** [comment]
Might switch to https://github.com/AdeleD/react-paginate
