### ISSUE TITLE
New forum "updated time" seems broken on mobile devices.

### ISSUE THREAD

**Issue by Se8870** [openmultiplayer/web#511]
As you can see on this screenshot below when opening the discussion or topic, it seems like the forum itself is kinda broken.

![Screenshot_2021-11-26-04-59-24-42](https://user-images.githubusercontent.com/81698889/143503234-04a78b2c-36c5-43eb-b307-f5e5679e7d38.jpg)

**Comment by Southclaws** [comment]
#509
