### ISSUE TITLE
Button works when you click the text instead of the option itself

### ISSUE THREAD

**Issue by Fairuz-Afdhal** [openmultiplayer/web#513]
I don't know exactly what it's called, but I thought the screenshot will explain it
So if you click it like this
![image](https://user-images.githubusercontent.com/62930373/143665810-040a3869-a8e6-46df-80cf-86d05cc08b44.png)
It redirects okay, but when you click the option, it doesn't react anything
![image](https://user-images.githubusercontent.com/62930373/143665838-a617e14c-af12-4418-bb3b-bae3dc1ab50f.png)
This is the same with the language button as well

**Comment by Southclaws** [comment]
This seems to be a wrapping issue with <MenuItem />, the text node inside it is a link but the menu item itself isn't. Should be an easy fix: https://chakra-ui.com/docs/overlay/menu#menuitem-props
