### ISSUE TITLE
Warnings & Tips Key Tag Translation?!

### ISSUE THREAD

**Issue by iPollo** [openmultiplayer/web#55]
This is really a small and unimportant thing, but Warnings and Tips are only read on the wiki if they have the English key tag, which means that they cannot be translated. (Warnings, Tips, Caution etc.)

As I said, it is literally a small thing, but it is still an unusual part in the middle of a translated page.

**Comment by Southclaws** [comment]
This is now easier with custom templates - the new <VersionWarn> template is now simply just a piece of HTML with some admonition classes.

As for `:::` sections, we could just bring the admonition code into our codebase and add translation support so it uses the path/next.js locale to determine which word to use.
