### ISSUE TITLE
Code examples in docs should have syntax highlighting

### ISSUE THREAD

**Issue by mrreus** [openmultiplayer/web#569]
As in the title of the issue. I think this change will improve readability of code.

**Comment by LeonardSSH** [comment]
Definitely a syntax highlight will be implemented, but for PAWN I don't think there are any, so we've to make one (btw, it won't be that hard, the syntax being similar to C++, it will be a piece of cake) 😊

**Comment by adib-yg** [comment]
Resolved in #826
