### ISSUE TITLE
Dark theme on forum threads not working correctly

### ISSUE THREAD

**Issue by Burridge** [openmultiplayer/web#575]
Forum threads show up like this when using the dark theme. As far as I have seen everything else is fine.

![image](https://user-images.githubusercontent.com/4886682/161434296-6d9885d8-8d28-4a48-84fa-fa592ae90cdb.png)

**Comment by Burridge** [comment]
Apologies, I just spotted #573.

**Comment by LeonardSSH** [comment]
Will be solved in #573. Thx.
