### ISSUE TITLE
"View Repo" link incorrect on index. 

### ISSUE THREAD

**Issue by DobbysGamertag** [openmultiplayer/web#581]
![image](https://user-images.githubusercontent.com/4951376/161542448-69156cc3-79b8-4a7c-abfb-b0f8d7486f77.png)

It's the URL for the forum. Not the Github repo.

**Comment by LeonardSSH** [comment]
The repo is not yet public, so it is irrelevant where it redirects to.

**Comment by DobbysGamertag** [comment]
> The repo is not yet public, so it is irrelevant where it redirects to.

As of today 4th April 2020 the public beta has been released.

**Comment by LeonardSSH** [comment]
I think that link refers to the open source open.mp repo, not the beta server.

**Comment by DobbysGamertag** [comment]
> I think that link refers to the open source open.mp repo, not the beta server.

Looking at `index.tsx` now, I assume adding `https://github.com/openmultiplayer` as the URL rather than `/discussion` will work?
