### ISSUE TITLE
Announce endpoint not working.

### ISSUE THREAD

**Issue by ksenonadv** [openmultiplayer/web#582]
It looks like the IP address used in announce endpoint is not properly propagated.
The request is failing with the following error:
```
{"error":"failed to query server: failed to read response: read udp 172.21.0.16:37133-\u003e172.21.0.6:7777: read: connection refused"}
```
https://github.com/openmultiplayer/web/blob/6edde858439190c06943f172a264071682a8ac7f/server/src/api/legacy/h_postLegacy.go#L31

**Comment by Southclaws** [comment]
Ah yeah this needs to use CF-Connecting-IP header (or whatever it's called)

Cloudflare have docs on this: https://developers.cloudflare.com/fundamentals/get-started/http-request-headers/

**Comment by Southclaws** [comment]
Is this fixed now?
