### ISSUE TITLE
Previews of available styles and fonts don't work

### ISSUE THREAD

**Issue by reusoo** [openmultiplayer/web#589]
![Zrzut ekranu 2022-04-17 150228](https://user-images.githubusercontent.com/73140302/163715492-9026ff39-7ee6-43e5-a23d-02349ea3357b.png)

**Pages:**
https://open.mp/en/docs/scripting/functions/PlayerTextDrawFont
https://open.mp/en/docs/scripting/functions/TextDrawFont

**Proper previews should be displayed as like there:**
https://sampwiki.blast.hk/wiki/TextDrawFont
https://sampwiki.blast.hk/wiki/PlayerTextDrawFont

**Comment by leonardssh** [comment]
@Southclaws do we have these images on `assets.open.mp` ?

**Comment by Southclaws** [comment]
Should do, we used to for sure
