### ISSUE TITLE
PSQL Error

### ISSUE THREAD

**Issue by ryuuzu** [openmultiplayer/web#600]
Hey,

So just now I was trying to log in the open.mp website with GitHub but this error was seen. Just wanted to report it I hope I am in the right place.

`pql error: Error in connector: Error creating a database connection. (Timed out fetching a connection from the pool (connection limit: 10, in use: 10))`

![image](https://user-images.githubusercontent.com/71829472/165417517-1084c48f-84f8-486e-8eaa-995baadff5de.png)

**Comment by leonardssh** [comment]
@Southclaws 
https://github.com/openmultiplayer/web/blob/53bc7d80eae0723a1edd154a5e3cfb2b318dc3ed/server/src/web/web.go#L39

**Comment by leonardssh** [comment]
Also seems `/servers` doesn't work too.

![image](https://user-images.githubusercontent.com/35312043/165466562-9d188eab-cf2a-4fe7-bda0-4bc31f946ded.png)

**Comment by Southclaws** [comment]
Just a temporary DB outage, restarted.

Should switch to [CockroachDB cloud](https://www.cockroachlabs.com/product/) tbh.
