### ISSUE TITLE
Missing pickup type 23

### ISSUE THREAD

**Issue by reusoo** [openmultiplayer/web#620]
There's no pickup type 23 in the list of pickup types, but it's listed there: https://gtamods.com/wiki/0213.
https://open.mp/docs/scripting/resources/pickuptypes

**Comment by leonardssh** [comment]
https://sampwiki.blast.hk/wiki/PickupTypes

**Comment by NexiusTailer** [comment]
That's probably unused type or the same as the first in a list. Anyway, that seems the only place where it's mentioned and no any proper description is provided (except the fact it's just unpickable)
