### ISSUE TITLE
Partner Request: OMP

### ISSUE THREAD

**Issue by eksqtr** [openmultiplayer/web#670]
HostName: (Open:MP) City of Manila Roleplay
Address:  samp.equitygaming.net:7777
Players:  127 / 300
Ping:     83
Mode:     CoM-RP v2.9.769 R2 (Beta)
Language: English

**Comment by Southclaws** [comment]
For partner servers, please use the branding guidelines for open.mp, most importantly, the open.mp name must be styled as all lowercase with a dot (`.`) this has always been the brand style.

This is to avoid confusion with ["OpenMP"](https://www.openmp.org/) which is not affiliated with our mod in any way.

**Comment by eksqtr** [comment]
HostName: open.mp | City of Manila Roleplay
Address:  samp.equitygaming.net:7777
Players:  178 / 300
Ping:     60
Mode:     CoM-RP v2.9.769 R2 (Beta)
Language: English

Done.
