### ISSUE TITLE
Docs - Text draw area based on a 640x480

### ISSUE THREAD

**Issue by Leonardo541** [openmultiplayer/web#673]
In the documentation it says "text draw area based on a 640x480", when the correct is 640x448.

https://open.mp/docs/scripting/functions/TextDrawCreate
https://open.mp/docs/scripting/functions/TextDrawTextSize
https://open.mp/docs/scripting/functions/PlayerTextDrawTextSize

I'm assuming this is a bug in the SA-MP client that was never fixed to maintain compatibility with existing scripts.

**Comment by adib-yg** [comment]
Textdraws are designed according to a **640x480** canvas and they are scaled according to that.
