### ISSUE TITLE
api.open.mp not working in docs search

### ISSUE THREAD

**Issue by AmyrAhmady** [openmultiplayer/web#680]
It's reporting CORDS Missing Allow Origin (probably another issue with CF rules)
![image](https://user-images.githubusercontent.com/34688664/208407147-f1a56bcc-41b2-4dbe-a6e9-ffe66c0932d7.png)

**Comment by AmyrAhmady** [comment]
@Southclaws

**Comment by Southclaws** [comment]
https://api.open.mp/docs/search?q=position

seems to work

**Comment by Southclaws** [comment]
and CORS would cause /servers to fail too

**Comment by Southclaws** [comment]
oh it really is just that endpoint without a CORS header, not sure how that can happen as CORS is applied to the entire API surface, will investigate

**Comment by Southclaws** [comment]
<img width="574" alt="image" src="https://user-images.githubusercontent.com/1636971/210140509-9c8517a6-b9b4-4031-b98c-cd674ed882df.png">
