### ISSUE TITLE
adding images objects

### ISSUE THREAD

**Issue by adytzuPWN** [openmultiplayer/web#724]
also add picture to objects and where we can find them.

**Comment by kkmzero** [comment]
If you mean page 'SA-MP Objects', I'm pretty sure there's info section right at the top linking you to object database at dev.prineside.com with images, object IDs, places on map and other useful info. There are hundreds and hundreds of objects just in the SAMP.ide, not counting other IDE files.

**Comment by adib-yg** [comment]
https://dev.prineside.com/en/gtasa_samp_model_id/
