### ISSUE TITLE
Old links are (kinda) broken

### ISSUE THREAD

**Issue by kkmzero** [openmultiplayer/web#741]
Old links without the 'www.' URL prefix now redirect you to main page. For example, take any direct link which used to work before (https://open.mp/docs/scripting/resources/bodyparts) and you end up on main page instead on correct documentation page. Adding the 'www.' manually to address works fine but it's annoying. Is there any way of fixing this, please?

**Comment by Southclaws** [comment]
fixed.

curl -v https://open.mp/docs

307
Location: https://www.open.mp/docs
