### ISSUE TITLE
Update partner server IP

### ISSUE THREAD

**Issue by Hidacska** [openmultiplayer/web#744]
Hi!

Can you please update [HUN] NORTH RPG [PC/ANDROID] (https://www.open.mp/hu/servers/45.67.156.96:7777) servers ip address to 87.229.6.238:7777?

We are moved to another server in february.

Thank you!

**Comment by Southclaws** [comment]
- https://www.open.mp/partners
- https://www.open.mp/hu/servers/87.229.6.238:7777
