### ISSUE TITLE
Docs in Modern Standard Arabic?

### ISSUE THREAD

**Issue by midosvt** [openmultiplayer/web#790]
Hello, I am wondering if we can have this removed: https://github.com/openmultiplayer/web/tree/master/docs/translations/ar-TN

As it is not in line with 'Modern Standard Arabic'. Instead, I am personally willing to translate the content into 'Modern Standard Arabic' to ensure wider comprehension across all Arabic-speaking countries. The current translation appears to be predominantly in Tunisian dialect. For example, someone from Kuwait may have difficulty understanding the translation. But will not if the translation is in Modern Standard Arabic.

**Comment by ImOver00** [comment]
I initially started translating the scripts from English to the Tunisian dialect, more specifically in franco arabic (which uses Latin alphabet as you see), time went by (almost 2 years) and I became no more motivated to complete the translation process. I thought about translating it to standard Arabic but it would have been so tiring doing that alone, given the fact that I couldn't find any supporters during that period.

**Comment by midosvt** [comment]
> I initially started translating the scripts from English to the Tunisian dialect, more specifically in franco arabic (which uses Latin alphabet as you see), time went by (almost 2 years) and I became no more motivated to complete the translation process. I thought about translating it to standard Arabic but it would have been so tiring doing that alone, given the fact that I couldn't find any supporters during that period.
I can help you with that one, feel free to message me on discord. My username is justmido

**Comment by adib-yg** [comment]
Resolved in #867
