### ISSUE TITLE
Add notes to GetVehicleTrailer 

### ISSUE THREAD

**Issue by MicheleLaBarbera** [openmultiplayer/web#93]
Add below 'This function does not work for train' also 'This function will return 0 if a player isn't near (10mt or less) the vehicleid specified'.

**Comment by adib-yg** [comment]
![image](https://github.com/openmultiplayer/web/assets/92677767/636d880f-158e-4f1e-ad2b-29fac9774374)

I'm not sure what you mean by 
> _This function will return 0 if a player isn't near (10mt or less) the vehicleid specified_

This function is about vehicle trailers, not players.
